# Generated by Django 4.2 on 2023-05-01 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canban', '0002_alter_boardmodel_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardmodel',
            name='owner',
        ),
    ]
